language: python
python:
- 3.6
before_install:
- wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=/home/travis/miniconda3/bin:$PATH
- conda update --yes conda
install:
- conda env create --file=environment.yml
- source activate DeepForest
- cd keras_retinanet
- python setup.py build_ext --inplace
- cd ..
env: TRAVIS=true
script:
- pytest --ignore=keras-retinanet/