#Config file for DeepMeerkat train.py on local OSX

#Data generation - the number of workers for dask session
num_hipergator_workers: 20
training_csvs:
  - TEAK
  
#Keras
workers: 1
use_multiprocessing: False
max_queue_size: 10
num_GPUs: 1
save_image_path: snapshots/images/
save_snapshot_path: snapshots/images/

#Sliding Window Size and Ovelap
patch_size: 400
patch_overlap: 0.05
rgb_res: 0.1

#Preprocessing routines
preprocess:
  zero_area: True

#Select sites
hand_annotation_site:
  - SJER
pretraining_site:
  - SJER
evaluation_site:
  - SJER

#Training
training_images: 1
weights: /Users/ben/Documents/DeepLidar/snapshots/SJER_selfsupervised.h5
imagenet_weights: False
batch_size: 25
epochs: 1
backbone: resnet50
shuffle_training: True
score_threshold: 0.20

#Evaluation
evaluation_images: 0
shuffle_evaluation: False
validation_percent: 5 #For hand annotation neon_MAP
#Non-max suppression, threshold for the IoU value to determine when a box should be suppressed.
nms_threshold: 0.1

#LIDAR density
min_density: 100

#Data Paths
SJER:
  h5: /Users/Ben/Downloads/SJER/
  hand_annotations: /Users/Ben/Documents/DeepLidar/data/SJER/training/
  training_csvs: /Users/Ben/Documents/DeepLidar/data/SJER/training/
  training:
    RGB: /Users/Ben/Documents/DeepLidar/data/SJER/training/
    LIDAR: /Users/Ben/Documents/DeepLidar/data/SJER/training/
  evaluation:
    RGB: /Users/Ben/Documents/DeepLidar/data/SJER/plots/
    LIDAR: /Users/Ben/Documents/DeepLidar/data/SJER/plots/
TEAK:
  h5: /Users/Ben/Downloads/TEAK/
  training_csvs: /Users/Ben/Documents/DeepLidar/data/TEAK/training/
  hand_annotations: /Users/Ben/Documents/DeepLidar/data/TEAK/training/
  training:
    RGB: /Users/Ben/Documents/DeepLidar/data/TEAK/training/
    LIDAR: /Users/Ben/Documents/DeepLidar/data/TEAK/training/
  evaluation:
    RGB: /Users/Ben/Documents/DeepLidar/data/TEAK/plots/
    LIDAR: /Users/Ben/Documents/DeepLidar/data/TEAK/plots/
