name: DeepLidar
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.2.1=py_0
  - asn1crypto=0.24.0=py36_1003
  - attrs=18.2.0=py_0
  - blas=1.1=openblas
  - boost-cpp=1.67.0=h3a22d5f_0
  - boto3=1.9.48=py_0
  - botocore=1.12.49=py_0
  - bzip2=1.0.6=h470a237_2
  - ca-certificates=2018.10.15=ha4d7672_0
  - cairo=1.14.12=he6fea26_5
  - certifi=2018.10.15=py36_1000
  - cffi=1.11.5=py36h5e8e0c9_1
  - chardet=3.0.4=py36_1003
  - click=7.0=py_0
  - click-plugins=1.0.4=py_0
  - cligj=0.5.0=py_0
  - cloudpickle=0.6.1=py_0
  - cryptography=2.3.1=py36hdffb7b8_0
  - cryptography-vectors=2.3.1=py36_1000
  - curl=7.62.0=h74213dd_0
  - cycler=0.10.0=py_1
  - cytoolz=0.9.0.1=py36h470a237_1
  - dask-core=0.20.2=py_0
  - dbus=1.13.0=h3a4f0e9_0
  - decorator=4.3.0=py_0
  - descartes=1.1.0=py_2
  - docutils=0.14=py36_1001
  - expat=2.2.5=hfc679d8_2
  - fiona=1.7.13=py36hb00a9d7_4
  - fontconfig=2.13.1=h65d0f4c_0
  - freetype=2.9.1=h6debe1e_4
  - freexl=1.0.5=h470a237_2
  - gdal=2.2.4=py36hb00a9d7_1
  - geopandas=0.4.0=py_1
  - geos=3.6.2=hfc679d8_3
  - geotiff=1.4.2=h700e5ad_5
  - gettext=0.19.8.1=h5e8e0c9_1
  - giflib=5.1.4=h470a237_1
  - glib=2.55.0=h464dc38_2
  - gst-plugins-base=1.12.5=hde13a9d_0
  - gstreamer=1.12.5=h61a6719_0
  - hdf4=4.2.13=h951d187_2
  - hdf5=1.10.2=hc401514_2
  - icu=58.2=hfc679d8_0
  - idna=2.7=py36_1002
  - imageio=2.4.1=py36_1000
  - ipython_genutils=0.2.0=py_1
  - jmespath=0.9.3=py_1
  - joblib=0.13.0=py_0
  - jpeg=9c=h470a237_1
  - json-c=0.12.1=h470a237_1
  - jsonschema=3.0.0a3=py36_1000
  - jupyter_core=4.4.0=py_0
  - kealib=1.4.9=h0bee7d0_2
  - kiwisolver=1.0.1=py36h2d50403_2
  - krb5=1.16.2=hbb41f41_0
  - lastools=20171231=hfc679d8_0
  - libcurl=7.62.0=hbdb9355_0
  - libedit=3.1.20170329=haf1bffa_1
  - libffi=3.2.1=hfc679d8_5
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgdal=2.2.4=h25f9fa3_7
  - libgfortran=3.0.0=1
  - libiconv=1.15=h470a237_3
  - libkml=1.3.0=hccc92b1_8
  - libnetcdf=4.6.1=h628ed10_200
  - libpng=1.6.35=ha92aebf_2
  - libpq=10.5=he29860b_0
  - libspatialindex=1.8.5=hfc679d8_3
  - libspatialite=4.3.0a=hdfcc80b_23
  - libssh2=1.8.0=h5b517e9_3
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libtiff=4.0.9=he6b73bb_2
  - libuuid=2.32.1=h470a237_2
  - libxcb=1.13=h470a237_2
  - libxml2=2.9.8=h422b904_5
  - llvmlite=0.25.0=py36hd28b015_1
  - matplotlib=3.0.2=py36h8a2030e_1
  - matplotlib-base=3.0.2=py36h20b835b_1
  - munch=2.3.2=py_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hfc679d8_1
  - networkx=2.2=py_1
  - numba=0.40.0=py36hf8a1672_0
  - numpy=1.15.4=py36_blas_openblashb06ca3d_0
  - olefile=0.46=py_0
  - openblas=0.3.3=ha44fe06_1
  - openjpeg=2.3.0=h0e734dc_3
  - openssl=1.0.2p=h470a237_1
  - pandas=0.23.4=py36hf8a1672_0
  - pcre=8.41=hfc679d8_3
  - pillow=5.3.0=py36hc736899_0
  - pip=18.1=py36_1000
  - pixman=0.34.0=h470a237_3
  - plotly=3.4.1=py_0
  - poppler=0.61.1=h4d7e492_4
  - poppler-data=0.4.9=0
  - proj4=4.9.3=h470a237_8
  - psycopg2=2.7.6.1=py36hdffb7b8_0
  - pthread-stubs=0.4=h470a237_1
  - pycparser=2.19=py_0
  - pyopengl=3.1.1a1=py_1
  - pyopenssl=18.0.0=py36_1000
  - pyparsing=2.3.0=py_0
  - pyproj=1.9.5.1=py36h508ed2a_6
  - pyqt=5.6.0=py36h8210e8a_7
  - pyqtgraph=0.10.0=py_5
  - pyrsistent=0.14.6=py36h470a237_0
  - pysal=1.14.4.post2=py36_1001
  - pysocks=1.6.8=py36_1002
  - python=3.6.7=h5001a0f_1
  - python-dateutil=2.7.5=py_0
  - pytz=2018.7=py_0
  - pywavelets=1.0.1=py36h7eb728f_0
  - qt=5.6.2=hf70d934_9
  - rasterio=1.0.9=py36h1b5fcde_0
  - readline=7.0=haf1bffa_1
  - requests=2.20.1=py36_1000
  - retrying=1.3.3=py_2
  - rtree=0.8.3=py36_1000
  - s3transfer=0.1.13=py36_1001
  - scikit-image=0.14.1=py36hfc679d8_1
  - scikit-learn=0.20.0=py36_blas_openblash00c3548_201
  - scipy=1.1.0=py36_blas_openblashb06ca3d_202
  - setuptools=40.6.2=py36_0
  - shapely=1.6.4=py36h164cb2d_1
  - sip=4.18.1=py36hfc679d8_0
  - six=1.11.0=py36_1001
  - snuggs=1.4.1=py_1
  - sqlalchemy=1.2.14=py36h470a237_0
  - sqlite=3.25.3=hb1c47c0_0
  - tk=8.6.9=ha92aebf_0
  - toolz=0.9.0=py_1
  - tornado=5.1.1=py36h470a237_0
  - traitlets=4.3.2=py36_1000
  - urllib3=1.23=py36_1001
  - wheel=0.32.3=py36_0
  - xerces-c=3.2.0=h5d6a6da_2
  - xorg-kbproto=1.0.7=h470a237_2
  - xorg-libice=1.0.9=h470a237_4
  - xorg-libsm=1.2.3=h8c8a85c_0
  - xorg-libx11=1.6.6=h470a237_0
  - xorg-libxau=1.0.8=h470a237_6
  - xorg-libxdmcp=1.1.2=h470a237_7
  - xorg-libxext=1.3.3=h470a237_4
  - xorg-libxrender=0.9.10=h470a237_2
  - xorg-renderproto=0.11.1=h470a237_2
  - xorg-xextproto=7.3.0=h470a237_2
  - xorg-xproto=7.0.31=h470a237_7
  - xz=5.2.4=h470a237_1
  - zlib=1.2.11=h470a237_3
  - pip:
    - alabaster==0.7.12
    - babel==2.6.0
    - comet-git-pure==0.19.8
    - comet-ml==1.0.38
    - configobj==5.0.6
    - coverage==4.0.3
    - dask==0.20.2
    - everett==0.9
    - h5py==2.8.0
    - imagesize==1.1.0
    - jinja2==2.10
    - keras-retinanet==0.4.1
    - laspy==1.5.1
    - markupsafe==1.1.0
    - netifaces==0.10.7
    - nvidia-ml-py3==7.352.0
    - packaging==18.0
    - plyfile==0.6
    - psutil==5.4.8
    - pyfor==0.3.1
    - pygments==2.2.0
    - python-coveralls==2.9.1
    - pyyaml==3.13
    - slidingwindow==0.0.13
    - snowballstemmer==1.2.1
    - sphinx==1.8.2
    - sphinx-rtd-theme==0.4.2
    - sphinxcontrib-websupport==1.1.0
    - websocket-client==0.54.0
    - wurlitzer==1.0.2
    - xmltodict==0.11.0
prefix: /home/b.weinstein/miniconda/envs/DeepLidar

