name: DeepForest
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - sphinx
  - recommonmark
  - pyyaml
  - pytest
  - numpydoc
  - cython>=0.28
  - h5py=2.10.0
  - xmltodict
  - tqdm
  - numpy
  - pillow
  - pip
  - matplotlib
  - sphinx_rtd_theme
  - pandas
  - twine
  - psutil
  - pip:
    - keras-resnet
    - opencv-python
    - slidingwindow
    - keras==2.3.0
    - tensorflow==1.14
    - sphinx-markdown-tables
    - bumpversion
    - git+git://github.com/bw4sz/keras-retinanet.git
