name: DeepForest_pytorch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - sphinx
  - recommonmark
  - pyyaml>=5.1.0
  - pytest
  - numpydoc
  - h5py
  - xmltodict
  - tqdm
  - numpy
  - pillow
  - pip
  - matplotlib
  - sphinx_rtd_theme
  - pandas
  - twine
  - opencv
  - psutil
  - pytorch
  - torchvision
  - slidingwindow
  - bumpversion
  - scikit-image
  
