name: DeepForest
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx
  - docutils<0.18
  - recommonmark
  - pyyaml>=5.1.0
  - pytest
  - pytest-profiling
  - furo
  - numpydoc
  - geopandas
  - h5py
  - xmltodict
  - tqdm
  - numpy
  - pillow
  - pip
  - pytorch-lightning>1.5.0
  - matplotlib
  - sphinx_rtd_theme
  - opencv>=4.5.4
  - pandas
  - twine
  - rtree
  - rasterio
  - psutil
  - pytorch
  - torchvision>=0.13
  - slidingwindow
  - bumpversion
  - yapf
  - pip:
    - sphinx-markdown-tables
    - imagecodecs
    - albumentations>=1.0.0
    - pycocotools
