name: DeepForest
channels:
  - defaults
dependencies:
  - alabaster=0.7.12=py36_0
  - asn1crypto=0.24.0=py36_0
  - atomicwrites=1.3.0=py36_1
  - attrs=19.1.0=py36_1
  - babel=2.7.0=py_0
  - ca-certificates=2019.8.28=0
  - certifi=2019.9.11=py36_0
  - cffi=1.12.3=py36hb5b8e2f_0
  - chardet=3.0.4=py36_1003
  - cryptography=2.7=py36ha12b0ac_0
  - docutils=0.15.2=py36_0
  - idna=2.8=py36_0
  - imagesize=1.1.0=py36_0
  - importlib_metadata=0.23=py36_0
  - jinja2=2.10.1=py36_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - markupsafe=1.1.1=py36h1de35cc_0
  - more-itertools=7.2.0=py36_0
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1d=h1de35cc_2
  - packaging=19.2=py_0
  - pip=19.2.3=py36_0
  - pluggy=0.13.0=py36_0
  - py=1.8.0=py36_0
  - pycparser=2.19=py36_0
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.2=py_0
  - pysocks=1.7.1=py36_0
  - pytest=5.2.0=py36_0
  - python=3.6.9=h359304d_0
  - pytz=2019.2=py_0
  - readline=7.0=h1de35cc_5
  - requests=2.22.0=py36_0
  - setuptools=41.2.0=py36_0
  - six=1.12.0=py36_0
  - snowballstemmer=1.9.1=py_0
  - sphinx=2.2.0=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - sqlite=3.29.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - urllib3=1.24.2=py36_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - wheel=0.33.6=py36_0
  - xz=5.2.4=h1de35cc_4
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/ben/miniconda3/envs/DeepForest

