name: DeepForest
channels:
  - conda-forge
  - defaults
dependencies:
  - bump-my-version
  - docutils<0.18
  - geopandas
  - huggingface_hub>=0.25.0
  - h5py
  - matplotlib
  - nbmake
  - nbsphinx
  - numpy
  - numpydoc
  - pandas
  - pillow>6.2.0
  - pip
  - psutil
  - pydata-sphinx-theme
  - pytest
  - pytest-profiling
  - pytorch::pytorch
  - pytorch-lightning>1.5.8
  - pyyaml>=5.1.0
  - rasterio
  - recommonmark
  - rtree
  - slidingwindow
  - setuptools
  - sphinx
  - sphinx_rtd_theme
  - sphinx-design
  - pytorch::torchvision
  - tqdm
  - tensorboard
  - twine
  - xmltodict
  - yapf
  - pip:
    - sphinx-markdown-tables
    - albumentations>=1.0.0,<2.0.0
    - comet_ml
    - pycocotools
    - aiolimiter
    - aiohttp
    - supervision
    - pre-commit
    - nbqa
    - Pygments
    - docformatter
    - opencv-python-headless
    - safetensors
    - myst-parser
